### ISSUE TITLE
Airplay 2

### ISSUE THREAD

**Issue by lorenzoCuevas** [balena-labs-projects/balena-sound#419]
Hi I would like to ask that do you support airplay 2?

**Comment by tmigone** [comment]
Hi @lorenzoCuevas, balenaSound uses `shairport-sync` under the hood so it's up to them to add support for Airplay 2. Here is the relevant issue on their repository: https://github.com/mikebrady/shairport-sync/issues/1150

**Comment by valkjsaaa** [comment]
any update? airplay2 is already supported on `shairport-sync`

**Comment by fabienheureux** [comment]
Done in https://github.com/balena-labs-projects/balena-sound/pull/621

**Comment by maggie0002** [comment]
Closed by: https://github.com/balena-labs-projects/balena-sound/pull/621
