### ISSUE TITLE
Intel NUC Build failing

### ISSUE THREAD

**Issue by Chumba** [balena-labs-projects/balena-sound#604]
**Describe the problem**
I'm unable to deploy on NUC, it seems like audio-amd64 and bluetooth amd-64 had some links change today and balena-sound needs to be updated (I'm a complete noob here so forgive me if my conclusions are erroneous)

**To Reproduce**
1. Attempt to deploy balena-sound on a NUC based client

**Expected behavior**
balena-sound successfully deploys

**Screenshots**
![image](https://user-images.githubusercontent.com/8037968/202075947-3385e0bb-599e-4845-83af-44432014088f.png)

**Device information**
 - Board (hardware info): NUC
 - Device type (as seen in balenaCloud): Intel NUC
 -  balenaOS version: balenaOS 2.105.31+rev1

Build Overview:
[Info]              Starting build for testFleet, user g_bryan_charalambous
[Info]              Dashboard link: https://dashboard.balena-cloud.com/apps/1990690/devices
[Info]              Building on x64_01
[Info]              No suitable previous release for caching, skipping cache pull
[Info]              Starting to build hostname
[Info]              Starting to build multiroom-client
[Info]              Starting to build audio
[Info]              Starting to build bluetooth
[Info]              Starting to build airplay
[Info]              Starting to build spotify
[Info]              Starting to build multiroom-server
[Info]              Starting to build sound-supervisor
[Success]           Successfully built service hostname
[Success]           Successfully built service spotify
[Success]           Successfully built service airplay
[Success]           Successfully built service multiroom-client
[Success]           Successfully built service multiroom-server
[Success]           Successfully built service sound-supervisor
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: audio
[Error]                 Error: pull access denied for bh.cr/balenablocks/audio-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[Error]               Service: bluetooth
[Error]                 Error: pull access denied for bh.cr/balenablocks/bluetooth-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[Info]              Built on x64_01
[Error]             Not deploying release.

**Comment by Chumba** [comment]
Relevant PRs from the affected projects

https://github.com/balena-labs-projects/bluetooth/pull/29
https://github.com/balena-labs-projects/audio/pull/102

**Comment by Chumba** [comment]
Sorry fat fingered the closed button

**Comment by nucleardreamer** [comment]
@Chumba you caught it alright. We are in the middle of transitioning some containers between different repos and this project was a little lagged to get updated there. Should be resolved now!

**Comment by Chumba** [comment]
Thanks for the update! Having lots of fun with balena, really cool stuff you guys got going on.
