### ISSUE TITLE
Upgrade Shairport Sync to version 4.1

### ISSUE THREAD

**Issue by fabienheureux** [balena-labs-projects/balena-sound#607]
## Description 
Shairport Sync is out now, it could be great to support it in balena sound 
- https://github.com/mikebrady/shairport-sync/releases/tag/4.1 
- We are currently using the version 3.3.8 https://github.com/balena-labs-projects/balena-sound/blob/master/plugins/airplay/Dockerfile.template#LL1 
- It could help address https://github.com/balena-labs-projects/balena-sound/issues/419, https://github.com/balena-labs-projects/balena-sound/issues/540 and add more control over multiroom (https://github.com/balena-labs-projects/balena-sound/issues/404) - It would mean to delegate this feature to AP though

## Roadmap 
- [x] Bump the version in the Dockerfile -  https://github.com/balena-labs-projects/balena-sound/blob/master/plugins/airplay/Dockerfile.template#LL1 
- [x] ~~Add NQPTP _AirPlay 2 operation requires a companion program called NQPTP and requires a somewhat more powerful system. Please see [AIRPLAY2.md](https://github.com/mikebrady/shairport-sync/blob/master/AIRPLAY2.md) for more._~~ It seems that NQPTP is included in the shairport-sync Dockerfile https://github.com/mikebrady/shairport-sync/blob/master/docker/Dockerfile#L43 

I would be happy to help but I am unsure where to start. 
Is there some guidance other than https://github.com/balena-labs-projects/balena-sound/blob/master/CONTRIBUTING.md about how to build the project and run a modified balena-sound version ? 
Thanks !

**Comment by maggie0002** [comment]
Thanks for taking a look at this, it is very much appreciated. 

You can clone this repository, make amendments to it, and then push it to your own fleet for testing: https://www.balena.io/docs/learn/deploy/deployment/#balena-push

**Comment by fabienheureux** [comment]
Thank for your help, I did not think of checking Balena's support pages...
I will try this as soon as I can !

**Comment by Neustradamus** [comment]
To follow!

**Comment by maggie0002** [comment]
Closed by: https://github.com/balena-labs-projects/balena-sound/pull/621
