### ISSUE TITLE
Spotify module fails with 101 exit code

### ISSUE THREAD

**Issue by MrJynxZ** [balena-labs-projects/balena-sound#612]
**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**
1. Go to '...' after adding a device with a Raspberry Pi 4 using the latest (recommended) and previous revision.
2. Click on '....' the device shows up on the balena dashboard
3. Scroll down to '....' when adding audio-sound to it, the compilation fails on the Spotify module with a 101 returned code

**Expected behavior**

**Screenshots**

**Device information**
 - Board (hardware info): [e.g. Raspberry Pi 4B- 8GB]
 - Device type (as seen in balenaCloud): [e.g. Raspberry Pi 4 (using 64bit OS)]
 - balenaOS version: [
 - balena-cloud-balena-sound-raspberrypi4-64-2.107.10+rev3-v14.4.4.img
 - balena-cloud-balena-sound-raspberrypi4-64-2.106.2-v14.3.0.img
 - both failed the same way
[balena-sound_release-log_spotify-512ce43.txt](https://github.com/balena-labs-projects/balena-sound/files/10147349/balena-sound_release-log_spotify-512ce43.txt)
]
all other modules passed the compilation

**Additional context**

**Comment by elkir0** [comment]
Same With Rpi3 B+ 

[Success]           Successfully built service hostname
[Success]           Successfully built service audio
[Success]           Successfully built service multiroom-client
[Success]           Successfully built service multiroom-server
[Success]           Successfully built service bluetooth
[Success]           Successfully built service sound-supervisor
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: spotify
[Error]                 Error: The command '/bin/sh -c cargo build     --release     --features alsa-backend,pulseaudio-backend     --verbose' returned a non-zero code: 101
[Info]              Ran locally emulated build
[Error]             Not deploying release.

**Comment by btraquair** [comment]
I am seeing the exact same behavior with raspberry pi v1

**Comment by btraquair** [comment]
I've just tried to deploy from balena. Spotify built and installed properly!
